[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
chrono = "0.4"
directories = "6"
futures = "0.3"
iced = { version = "0.14", features = ["tokio"] }
prost = "0.14"
prost-build = "0.14"
protox = "0.9"
rand = "0.9"
reqwest = { version = "0.13", default-features = false, features = [
    "rustls-no-provider",
    "http2",
] }
rustls = { version = "0.23", default-features = false, features = [
    "ring",
    "std",
    "tls12",
    "logging",
] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "sync",
] }
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-webpki-roots"] }
toml = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"
webpki-roots = "0.26"

vorcall-core = { path = "crates/vorcall-core" }
vorcall-proto = { path = "crates/vorcall-proto" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
