//! The Vorcall creature: palette, mark, window icon and the entrance animation.
//! `data.rs` is generated by `assets/brand/gen.py`.

#[rustfmt::skip]
mod data;
pub mod entrance;
pub mod icon;
pub mod loading;
pub mod mark;
pub mod palette;
