[package]
name = "vorcall-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "vorcall"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cpal.workspace = true
futures.workspace = true
iced.workspace = true
image.workspace = true
notify-rust.workspace = true
rand.workspace = true
rfd.workspace = true
rodio.workspace = true
rubato.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tiny-skia.workspace = true
tokio.workspace = true
tracing.workspace = true
vorcall-core.workspace = true
vorcall-hotkey.workspace = true
vorcall-screen.workspace = true
vorcall-voice.workspace = true
