[package]
name = "vorcall-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "vorcall"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
futures.workspace = true
iced.workspace = true
notify-rust.workspace = true
rodio.workspace = true
rustls.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vorcall-core.workspace = true
