//! The brand icon set, baked into the binary.
//!
//! `assets/icons/*.svg` is generated by `assets/brand/gen.py icons`: a 24-unit
//! grid, stroke only, `stroke="currentColor"`. iced recolours them through
//! `svg::Style { color }`, so one file serves every theme and every state.

use std::sync::LazyLock;

use iced::widget::svg;
use iced::{Color, Element};

use crate::app::Message;
use crate::theme::styles;

/// Every icon the interface uses. The order is the order of [`FILES`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Icon {
    Hash,
    Speaker,
    SpeakerOff,
    Mic,
    MicOff,
    Headphones,
    HeadphonesOff,
    Screen,
    ScreenOff,
    ChevronDown,
    ChevronRight,
    Plus,
    Gear,
    Bell,
    BellOff,
    Users,
    User,
    Search,
    Reply,
    Edit,
    Trash,
    Smile,
    Paperclip,
    Close,
    Check,
    Dots,
    Shield,
    Crown,
    Pin,
    Expand,
    Link,
    Ban,
    Boot,
    Move,
    Star,
    Drag,
    ArrowUp,
    ArrowDown,
    Image,
    Palette,
    Keyboard,
    Logout,
    Info,
    Warning,
}

/// How many icons there are, which is how many handles are built.
pub const COUNT: usize = 44;

/// The bytes of every icon, in [`Icon`]'s own order. `include_bytes!` is relative
/// to this file: `src/` -> `vorcall-app/` -> `crates/` -> `client/` -> the
/// repository root.
const FILES: [&[u8]; COUNT] = [
    include_bytes!("../../../../assets/icons/hash.svg"),
    include_bytes!("../../../../assets/icons/speaker.svg"),
    include_bytes!("../../../../assets/icons/speaker_off.svg"),
    include_bytes!("../../../../assets/icons/mic.svg"),
    include_bytes!("../../../../assets/icons/mic_off.svg"),
    include_bytes!("../../../../assets/icons/headphones.svg"),
    include_bytes!("../../../../assets/icons/headphones_off.svg"),
    include_bytes!("../../../../assets/icons/screen.svg"),
    include_bytes!("../../../../assets/icons/screen_off.svg"),
    include_bytes!("../../../../assets/icons/chevron_down.svg"),
    include_bytes!("../../../../assets/icons/chevron_right.svg"),
    include_bytes!("../../../../assets/icons/plus.svg"),
    include_bytes!("../../../../assets/icons/gear.svg"),
    include_bytes!("../../../../assets/icons/bell.svg"),
    include_bytes!("../../../../assets/icons/bell_off.svg"),
    include_bytes!("../../../../assets/icons/users.svg"),
    include_bytes!("../../../../assets/icons/user.svg"),
    include_bytes!("../../../../assets/icons/search.svg"),
    include_bytes!("../../../../assets/icons/reply.svg"),
    include_bytes!("../../../../assets/icons/edit.svg"),
    include_bytes!("../../../../assets/icons/trash.svg"),
    include_bytes!("../../../../assets/icons/smile.svg"),
    include_bytes!("../../../../assets/icons/paperclip.svg"),
    include_bytes!("../../../../assets/icons/close.svg"),
    include_bytes!("../../../../assets/icons/check.svg"),
    include_bytes!("../../../../assets/icons/dots.svg"),
    include_bytes!("../../../../assets/icons/shield.svg"),
    include_bytes!("../../../../assets/icons/crown.svg"),
    include_bytes!("../../../../assets/icons/pin.svg"),
    include_bytes!("../../../../assets/icons/expand.svg"),
    include_bytes!("../../../../assets/icons/link.svg"),
    include_bytes!("../../../../assets/icons/ban.svg"),
    include_bytes!("../../../../assets/icons/boot.svg"),
    include_bytes!("../../../../assets/icons/move.svg"),
    include_bytes!("../../../../assets/icons/star.svg"),
    include_bytes!("../../../../assets/icons/drag.svg"),
    include_bytes!("../../../../assets/icons/arrow_up.svg"),
    include_bytes!("../../../../assets/icons/arrow_down.svg"),
    include_bytes!("../../../../assets/icons/image.svg"),
    include_bytes!("../../../../assets/icons/palette.svg"),
    include_bytes!("../../../../assets/icons/keyboard.svg"),
    include_bytes!("../../../../assets/icons/logout.svg"),
    include_bytes!("../../../../assets/icons/info.svg"),
    include_bytes!("../../../../assets/icons/warning.svg"),
];

/// One handle per icon, built once: `svg::Handle::from_memory` hashes the bytes,
/// and a rendered row must not pay for that.
static HANDLES: LazyLock<[svg::Handle; COUNT]> =
    LazyLock::new(|| FILES.map(svg::Handle::from_memory));

impl Icon {
    /// Where this icon sits in [`FILES`].
    pub fn index(self) -> usize {
        self as usize
    }

    /// The shared handle, cheap to clone.
    pub fn handle(self) -> svg::Handle {
        HANDLES[self.index()].clone()
    }
}

/// One icon, square, in one colour.
pub fn icon<'a>(icon: Icon, size: f32, color: Color) -> Element<'a, Message> {
    svg(icon.handle())
        .width(size)
        .height(size)
        .style(styles::svg(color))
        .into()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every `include_bytes!` points at a real icon, and the array lines up with
    /// the enum.
    #[test]
    fn every_icon_has_bytes() {
        let icons = [
            Icon::Hash,
            Icon::Speaker,
            Icon::SpeakerOff,
            Icon::Mic,
            Icon::MicOff,
            Icon::Headphones,
            Icon::HeadphonesOff,
            Icon::Screen,
            Icon::ScreenOff,
            Icon::ChevronDown,
            Icon::ChevronRight,
            Icon::Plus,
            Icon::Gear,
            Icon::Bell,
            Icon::BellOff,
            Icon::Users,
            Icon::User,
            Icon::Search,
            Icon::Reply,
            Icon::Edit,
            Icon::Trash,
            Icon::Smile,
            Icon::Paperclip,
            Icon::Close,
            Icon::Check,
            Icon::Dots,
            Icon::Shield,
            Icon::Crown,
            Icon::Pin,
            Icon::Expand,
            Icon::Link,
            Icon::Ban,
            Icon::Boot,
            Icon::Move,
            Icon::Star,
            Icon::Drag,
            Icon::ArrowUp,
            Icon::ArrowDown,
            Icon::Image,
            Icon::Palette,
            Icon::Keyboard,
            Icon::Logout,
            Icon::Info,
            Icon::Warning,
        ];

        assert_eq!(icons.len(), COUNT);
        for (index, icon) in icons.into_iter().enumerate() {
            assert_eq!(icon.index(), index, "{icon:?} is in enum order");
            let bytes = FILES[icon.index()];
            assert!(!bytes.is_empty(), "{icon:?} has bytes");
            let head = std::str::from_utf8(&bytes[..5]).expect("an SVG is text");
            assert_eq!(head, "<svg ", "{icon:?} is an SVG");
            assert!(
                bytes.windows(12).any(|window| window == b"currentColor"),
                "{icon:?} is recoloured by the theme"
            );
        }
    }
}
